### ISSUE TITLE
Ruby 1.9.3 is no longer maintained

### ISSUE THREAD

**Issue by albinekb** [trogdoro/xiki#107]
Got this warning when installing ruby 1.9.3 with RVM.

WARNING: Please be aware that you just installed a ruby that is no longer maintained (2014-02-23), for a list of maintained rubies visit:

    http://bugs.ruby-lang.org/projects/ruby/wiki/ReleaseEngineering

Please consider upgrading to ruby-2.1.2 which will have all of the latest security patches.

**Comment by trogdoro** [comment]
Xiki now works with ruby 2.0, 2.1, and 2.2 (and also still 1.9).
