### ISSUE TITLE
Error when starting xiki 

### ISSUE THREAD

**Issue by kdmcdow** [trogdoro/xiki#109]
I Installed xiki per git instructions on OS X 10.9 and when I attempt to run xiki I get the following error:

/Users/USERNAME/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- daemons (LoadError)
	from /Users/USERNAME/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/USERNAME/xiki/etc/command/xiki_command.rb:101:in `run'
	from /Users/USERNAME/xiki/bin/xiki:34:in `<top (required)>'
	from /usr/local/bin/xiki:2:in `load'
	from /usr/local/bin/xiki:2:in `<main>'

Any thoughts?

**Comment by trogdoro** [comment]
Xiki is no longer uses Bundler. Try installing xiki using the one-line installer on xiki.com (or the github xiki readme).
