### ISSUE TITLE
Trouble running xiki

### ISSUE THREAD

**Issue by foriamroot** [trogdoro/xiki#110]
Hi:

Installed via git on Ubuntu 14.04 (Linux DARKSTARR503U 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux).

Dumps back to BASH right after starting:

expected xiki_process.rb to respond after we started it, but it is not responding
/home/jayer/xiki/etc/command/xiki_command.rb:162:in `gets': execution expired (Timeout::Error)
        from /home/jayer/xiki/etc/command/xiki_command.rb:162:in `block (2 levels) in get_response'
        from /home/jayer/xiki/etc/command/xiki_command.rb:157:in `open'
        from /home/jayer/xiki/etc/command/xiki_command.rb:157:in `block in get_response'
        from /home/jayer/xiki/etc/command/xiki_command.rb:154:in `get_response'
        from /home/jayer/xiki/etc/command/xiki_command.rb:127:in `run'
        from /home/jayer/xiki/bin/xiki:34:in `<top (required)>'
        from /usr/bin/xiki:2:in `load'
        from /usr/bin/xiki:2:in `<main>'

 ruby -v
1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

Thanks!

**Comment by trogdoro** [comment]
A new version has been pushed. This is an error from the old codebase.
