### ISSUE TITLE
OSX 10.6 "Menu doesn't exist yet"

### ISSUE THREAD

**Issue by nathvi** [trogdoro/xiki#116]
When I type in xiki in my Terminal I get this text:
"
> Interfaces
Xiki can be used from...
- A text editor
- The 'xiki' shell command
- The http://xiki/ url in your browser (experimental)

For more information type:

$ xiki docs

> Google Group and Twitter
Join the google group or follow @xiki on twitter for help with
installing and using, or just to chat or share your ideas:

http://groups.google.com/group/xiki/
http://twitter.com/xiki

> Troubleshooting
A couple commands to help you trouble-shoot:

% bundle install
% xiki restart
% xiki readme"
How do I actually get to xiki???

**Comment by trogdoro** [comment]
Grab the latest source andtry again! To use xiki from your terminal type "xsh".

$ xsh
