### ISSUE TITLE
Problem with (and fix for) installing on OSX with homebrew ruby

### ISSUE THREAD

**Issue by jdidion** [trogdoro/xiki#118]
I have homebrew ruby 2.1.3. When trying to install xiki, I got an error during bundle regarding json and it's need for ruby headers, which are out of date or missing on OSX. This fix worked for me:

https://gist.github.com/goshakkk/5763489

**Comment by trogdoro** [comment]
Your link shows people saying that grabbing the latest xcode fixes the problem as well. Can you try that?

**Comment by trogdoro** [comment]
This is probably no longer an issue. Try installing xiki using the one-line installer on xiki.com (or the github xiki readme).
