### ISSUE TITLE
cmd return not working in emacs

### ISSUE THREAD

**Issue by rosenstrauch** [trogdoro/xiki#119]
neither is meta return.

should this be working? do i need to look for errors in my setup?

i can use the mouse to double click but not the keyboard, is there something i can put into .emacs to force the correct keymapping? (it says keymapping undefined)

**Comment by trogdoro** [comment]
The key to use for expanding now is Ctrl+X. In xsh, you can see at the bottom of the screen what the main keys are (including Ctrl+X). Command+Return can't really be mapped reliably/consistently in the terminal, nor can meta+return.
