### ISSUE TITLE
Make installation script compatible with fish-shell 

### ISSUE THREAD

**Issue by douglascamata** [trogdoro/xiki#120]
As a fish-shell user and I'm having trouble with the installation, I'm able to improve the install script and make it work with `fish-shell` too.

**Comment by trogdoro** [comment]
What is the specific error you're seeing? Please grab the latest and try it now. Not sure if it'll work with fish now, but some install errors have been fixed.

**Comment by trogdoro** [comment]
It looks like since fish isn't compatible with bash, the "xsh" shell function will have to have an optional fish-language version - https://github.com/trogdoro/xiki/blob/master/bin/.xsh

**Comment by trogdoro** [comment]
Duplicate with #108.
