### ISSUE TITLE
Xsh fails to start

### ISSUE THREAD

**Issue by bimmlerd** [trogdoro/xiki#124]
Hi!
I wanted to try out xiki since a lot seems to have changed. However, starting `xsh` like the readme suggest doesn't work for me. But I had a little free time, so I investigated a little:

The bash script is working mostly fine, except that `$xiki_dir` is `.` if you start `xsh` with `bin/xsh` like it is recommended in the readme, and then all you get is a fresh emacsclient window. 
That happens because emacsclient fails to load "$xiki_dir/misc/emacs/start_xiki_daemon.el", complaining (once you don't redirect the output)

    *ERROR*: Cannot open load file: no such file or directory, ./misc/emacs/start_xiki_daemon.el

It seems that `load` doesn't support relative paths (I'm using `emacs-mac`, the yamamoto port). Hope this helps in resolving this issue :)

Other than that, looking forward to all this :+1:

**Comment by ericsimard** [comment]
Try adding the path to xsh to $PATH, then load xsh from anywhere. That fixed it for me.

**Comment by trogdoro** [comment]
This should work now without having do the work-around of adding it to $PATH first. Please try again and report back so I can close this issue!

**Comment by bimmlerd** [comment]
Yessir, that fixed whatever the problem was :+1: 
Thanks
