### ISSUE TITLE
xiki with ssh ?

### ISSUE THREAD

**Issue by ManuCart** [trogdoro/xiki#133]
Is that possible to use xiki over ssh or without emacs?

**Comment by trogdoro** [comment]
> Is that possible to use xiki over ssh

Sure, xiki shell (xsh) runs in a terminal, so you can ssh to a remote server and paste in the 1-line installer. Xsh also lets you browse files and run commands on remote servers, without installing anything on them. One way to do this is to type something like "xsh -/foo@foo.com/" in bash (or zsh).
