### ISSUE TITLE
annoying request for confirmation when deleting 

### ISSUE THREAD

**Issue by espinielli** [trogdoro/xiki#136]
Once I grab and execute one of my past commands I get the annoying request 

    rm: remove regular file ‘/Users/espin/xiki/misc/tmp/grabbed_commands.notes’?

One of my (life-saving) aliases is

```bash
alias rm='rm -i'
```

I wonder whether [line 81 of .xsh](https://github.com/trogdoro/xiki/blob/master/bin/.xsh#L81) should be modified to force the removal of `grabbed_commands.notes`...

**Comment by espinielli** [comment]
maybe I should simply skip aliases for non-interactive sessions with

```bash
[ -z "$PS1" ] && return
# my aliases below
# ...
```

I'll give it a try.

**Comment by espinielli** [comment]
no, it needs to be forced in [L81](https://github.com/trogdoro/xiki/blob/master/bin/.xsh#L81) as:

```bash
    rm -f $HOME/xiki/misc/tmp/grabbed_commands.notes
```

**Comment by espinielli** [comment]
same at [L49](https://github.com/trogdoro/xiki/blob/master/bin/.xsh#L49)

**Comment by trogdoro** [comment]
I added the "-f" flag. Closing the issue.
