### ISSUE TITLE
xsh -r fails with error 

### ISSUE THREAD

**Issue by dsummersl** [trogdoro/xiki#138]
When I run `zsh -r` I see the following in the lower left corner:

    Error running timer: (el4r-ruby-error)

**Comment by alexlafroscia** [comment]
:+1: Also seeing this with the latest Xiki from Github

**Comment by trogdoro** [comment]
> When I run zsh -r

I'm assuming you mean "xsh -r".

I just did a push - can you see if that fixed it?  After you grab the
latest xiki, run "xsh -reload" before you try again.

If that didn't fix it, can you run this and see what it says?

  $ xsh -i -r

The -i flag makes it better at displaying error messages, since it
doesn't create a cached process.

--Craig

**Comment by dsummersl** [comment]
Yeah I meant `xsh` :)

The error is gone with this update! But...when I run `xsh -i -r` it just shows the text `| See the key shortcuts at the bottom. (^G also runs in shell)` with some keys at the bottom.

I use zsh, tried it in bash and it does the same thing.

**Comment by alexlafroscia** [comment]
I'm still seeing the same thing as @dsummersl, `^R` doesn't actually show me any commands in ZSH

**Comment by trogdoro** [comment]
Can you run this?

$ echo $SAVEHIST

If the output is 0, try running this:

$ SAVEHIST=1000

Then type a couple commands, then do ^R and see if it shows you them.

If this fixes it let me know, and I'll update xsh to temporarily set
SAVEHIST if it's 0 in zsh.

--Craig

**Comment by dsummersl** [comment]
Darn, thats not it. My `$SAVEHIST` is already set to 1000, and the `history` command looks good.

**Comment by trogdoro** [comment]
Hmm... Can you run these 2 lines...

$ dir="$HOME/xiki/misc/logs"
$ fc -W "$dir/shell_external_log.notes"

And then tell me what the contents of this file look like?

  ~/xiki/misc/logs/shell_external_log.notes

--Craig

**Comment by dsummersl** [comment]
The contents look good to my unfamiliar eyes:

```
: 1428162324:0;R
: 1428174041:0;./scripts/screen.sh
: 1428174054:0;echo $SAVEHIST
: 1428174068:7;xsh -r
: 1428174080:0;history
: 1428240308:0;dir="$HOME/xiki/misc/logs"
: 1428240316:3;man fc
: 1428240323:0;fc -W "$dir/shell_external_log.notes"
: 1428240337:14;vim ~/xiki/misc/logs/shell_external_log.notes
: 1428240353:0;xsh -r
```

**Comment by alexlafroscia** [comment]
@trogdoro I did that and the contents of that file was extremely long, and contained some command line stuff from a _long_ time ago.  I can't be sure that there's nothing in there that I wouldn't want to just put on the internet, so I will refrain from uploading it if that's alright.  Is there something specific that I can look for?

**Comment by trogdoro** [comment]
> Is there something specific that I can look for?

I just wanted to make sure there were some commands in the file. That's the
file that xiki creates and then grabs your commands from, so it's good at
least that seems to be functioning. At this point it'd probably be easiest
for me to pair with one or both of you, so we can explore more easily. If
this works, email me and we'll set up a time to screenshare on skype or
google hangouts.

--Craig

**Comment by alexlafroscia** [comment]
What's your email address? Or email me, `alex [at] lafroscia.com`

**Comment by trogdoro** [comment]
This should be fixed. Can you try again?

The problem was related to zsh putting special characters into the history file, and xsh choking silently while reading it in.

**Comment by alexlafroscia** [comment]
@trogdoro it's working for me now in ZSH

**Comment by dsummersl** [comment]
me too! thanks so much you all.
