### ISSUE TITLE
Error after install: -bash: xsh: command not found

### ISSUE THREAD

**Issue by seriema** [trogdoro/xiki#141]
Hi,

I installed with the new one-liner: `cd ~; curl -LO https://github.com/trogdoro/xiki/archive/master.tar.gz; tar xzf master.tar.gz; xiki-master/bin/xsh`

I went through the installation steps. Some XIKI things didn't stay in my console, but this was the output:
````
$ cd ~; curl -LO https://github.com/trogdoro/xiki/archive/master.tar.gz; tar xzf master.tar.gz; xiki-master/bin/xsh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   121    0   121    0     0    142      0 --:--:-- --:--:-- --:--:--   142
  0     0    0  557k    0     0   192k      0 --:--:--  0:00:02 --:--:--  471k
Additional optional dependencies are recommended to
make xsh run more smoothly. It should take less than
a minute over a fast internet connection.

  install the dependencies
  proceed without them
  show them first

Type one of the underlined letters: i


==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/emacs-24.4.yosemite.bottle.3.tar.gz
######################################################################## 100.0%
==> Pouring emacs-24.4.yosemite.bottle.3.tar.gz
==> Caveats
To have launchd start emacs at login:
    ln -sfv /usr/local/opt/emacs/*.plist ~/Library/LaunchAgents
Then to load emacs now:
    launchctl load ~/Library/LaunchAgents/homebrew.mxcl.emacs.plist
==> Summary
🍺  /usr/local/Cellar/emacs/24.4: 3914 files, 104M
````

Somewhere it said to type `xsh` to run XIKI, but I only get this error: `-bash: xsh: command not found`.

**Comment by trogdoro** [comment]
> Somewhere it said to type xsh to run XIKI

You can do that once you followed the instructions that pop up after
running the one-line installer (they add ~/xiki-master to your PATH
var).

Here's an alternate way to run xsh, before you add it to your PATH:

~/xiki-master/bin/xsh

I'd recommend installing the latest though. I improved a couple
things, including the setup instructions.

The one-line installer has been updated as well. You can copy the
latest from xiki.com.

--Craig

**Comment by seriema** [comment]
Oh ok. But what I installed through that first one-liner, what'll happen to it? Can I remove it? Or will it just be overwritten with the new one-liner?

**Comment by trogdoro** [comment]
> what I installed through that first one-liner, what'll happen to it?
> will it just be overwritten with the new one-liner?

Yeah, it'll be over-written.  User customizations go into ~/xiki and won't
be lost, if you made any.

If you want to remove what the old installer did, it's just the
~/xiki-master dir, and ~/master.tar.gz, as well as any lingering xsh
processes.

--Craig

**Comment by seriema** [comment]
Thanks! I've installed with `cd ~; curl -LO https://github.com/trogdoro/xiki/archive/master.tar.gz ; tar xzf master.tar.gz; cd xiki-master/bin; ./clearxsh; ./xsh` and can now run `xsh`. Now I just need to figure out what to do with it ;)
