### ISSUE TITLE
one line installer bug (emacsclient -t)

### ISSUE THREAD

**Issue by masukomi** [trogdoro/xiki#143]
```shell
➜ cd ~; curl -LO https://github.com/trogdoro/xiki/archive/master.tar.gz ; tar xzf master.tar.gz; cd xiki-master/bin; ./clearxsh; ./xsh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   121    0   121    0     0    119      0 --:--:--  0:00:01 --:--:--   119
  0     0    0  559k    0     0   234k      0 --:--:--  0:00:02 --:--:--  937k
emacsclient: invalid option -- t
Try `emacsclient --help' for more information
```

I'm not an emacs user but apparently i installed some version of it at some point. I'd say which version but `emacs -version` just returns with no output. `emacsclient -V` on the other hand  returns "emacsclient 22.1" so maybe that's useful. 

I'm assuming the installer is just assuming the user has a recent enough version of emacs client if they have it installed.

**Comment by trogdoro** [comment]
I did a push yesterday that likely fixed this. Please try again!

--Craig

**Comment by trogdoro** [comment]
Anyone still getting this? If I don't hear anything I'll close the issue.

**Comment by masukomi** [comment]
sorry. yeah, just tried. I copy pasted the instruction from xiki.org and had the same result.

```shell
➜ cd ~; curl -LO https://github.com/trogdoro/xiki/archive/master.tar.gz ; tar xzf master.tar.gz; cd xiki-master/bin; ./clearxsh; ./xsh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   121    0   121    0     0    243      0 --:--:-- --:--:-- --:--:--   243
  0     0    0  559k    0     0   448k      0 --:--:--  0:00:01 --:--:-- 1851k
emacsclient: invalid option -- t
Try `emacsclient --help' for more information
```

**Comment by trogdoro** [comment]
Do you have time to screenshare today or tomorrow, so we can try and track this down?

**Comment by trogdoro** [comment]
Let me know when is a good time. Or if anyone else having this issue can pair with me to help me track it down, that would be great!

**Comment by masukomi** [comment]
sorry about the delay. I'm free after 2PM EST Wed and Thur if that works for you. Hit me up on twitter @masukomi and we can work out a time.

**Comment by masukomi** [comment]
I am happy to report it was user error :smile: 

I had installed the Emacs.app and in order to have an `emacs` command I could use on my shell i had a little bash script that did this:

    #!/bin/sh
    nohup /Applications/Emacs.app/Contents/MacOS/Emacs "$@" > /dev/null 2>&1 &

After getting rid of that it worked fine. As an aside i opened the Emacs.app afterwards and it claims to be `Version 24.3 (9.0)`  which doesn't seem that old, but what do I know. I'm a vim user. ;)
