### ISSUE TITLE
xsh gives me a blank window that does nothing

### ISSUE THREAD

**Issue by wagenet** [trogdoro/xiki#147]
I ran the one-line installer which, at the end runs `./xsh`. This gives me a blank window reporting as emacsclient. I can type, but see no obvious way to execute commands or even to exit.

**Comment by trogdoro** [comment]
Try again now. I just pushed a bugfix.

If that didn't fix it, please give me more info about your environment (os,
ruby version, emacs version).

--Craig

**Comment by wagenet** [comment]
The install works now. Thanks :)
