### ISSUE TITLE
Can't copy/paste bug examples

### ISSUE THREAD

**Issue by thams** [trogdoro/xiki#151]
On mac running xsh under iTerm, I did
xsh -e

which leads to an error screen and a backtrace. I want to paste that backtrace here in a bug report, but I can't select, copy and paste the block of text. Any attempt to right-click and Copy copies only one word.

Would appreciate help on how to do copy of a block of text, or to write out the screen to a file.

**Comment by JosephViolago** [comment]
Is this your error?

```
edited/
  - tried to run:
    : # /, so show the list...
    :
    : files = DiffLog.file_list :tree_format=>1
    : txt = files.join "\n"
  - error:
    | No such file or directory @ rb_sysopen - /Users/joev/xiki/misc/logs/difflog.notes
    |   Errno::ENOENT
  - backtrace:
    =/usr/local/Cellar/xiki/HEAD/lib/xiki/core/diff_log.rb:675:in `read'
    =/usr/local/Cellar/xiki/HEAD/lib/xiki/core/diff_log.rb:675:in `file_list'
    =/usr/local/Cellar/xiki/HEAD/commands/edited.rb:3:in `eval_inner'
    =/usr/local/Cellar/xiki/HEAD/lib/xiki/core/code.rb:299:in `module_eval'
    =/usr/local/Cellar/xiki/HEAD/lib/xiki/core/code.rb:299:in `eval_inner'
    =/usr/local/Cellar/xiki/HEAD/lib/xiki/core/code.rb:261:in `eval'
    =/usr/local/Cellar/xiki/HEAD/lib/xiki/handlers/ruby_handler.rb:30:in `handle_script'
    =/usr/local/Cellar/xiki/HEAD/lib/xiki/handlers/ruby_handler.rb:19:in `handle'
    =/usr/local/Cellar/xiki/HEAD/lib/xiki/core/menu.rb:1015:in `block in handle'
```

xiki uses emacs, you need to configure your `~/.emacs` to support shared clipboard.

http://apple.stackexchange.com/questions/85222/configure-emacs-to-cut-and-copy-text-to-mac-os-x-clipboard

**Comment by trogdoro** [comment]
In iTerm you can hold down option to select text to copy and paste, to
override the broken mouse terminal integration. At somepoint I'll upgrade
the installer to let people explicitly enable mouse support to avoid this.

--Craig

**Comment by thams** [comment]
Option key works. Closing this ticket and opening a new one with the actual bug, now that I can report it.
