### ISSUE TITLE
Executing unending processes from Xiki notes

### ISSUE THREAD

**Issue by echosa** [trogdoro/xiki#166]
I use `unison` for file syncing. I usually run `unison` in its own terminal, and leave it running throughout the work day. It continuously runs, watches for file changes, and syncs files on save. It outputs to the terminal when it syncs and when it's done syncing. 

When I execute `unison` from a Xiki note, Xiki just tells me the process is taking a long time, and I can press Esc to stop it. I obviously don't want to stop it. However, since it seems to be running in the background, I don't get the sync information displayed out to the terminal to watch for errors, etc.

Is it possible to start a constantly running process like unison from Xiki notes and either a.) see the output in Xiki like I would in bash, or 2.) exit back out to bash but still have the process running and the output going to stdout as usual?

**Comment by trogdoro** [comment]
Yes, "2.)" is possible. Type Ctrl+G  when your cursor is on the command,
and it will go back to your default shell and run it there.

Or, use an & as the prompt instead of a $, and then Ctrl+O or double
clicking will do that.

$ echo "Gets run inline unless you Ctrl+G"
& echo "Gets run back in bash or zsh"

--Craig

**Comment by echosa** [comment]
Oh, sweet. Ctrl-G is what I was needing! I should have known that, from the tutorial. :-P 

Great to know about the & prompts, though. I don't think that was in the tutorial.

Thanks!

**Comment by trogdoro** [comment]
No prob! Yeah, I should maybe add that to a more advanced section of the
tutorial.

I'm going to restructure the tutorial a little bit to make it use the
shortcuts at the bottom as a guide. I'm hoping that will lessen the
confusion people are telling me they're having in the tutorial regarding ^O
vs ^X vs ^G.

--Craig

**Comment by echosa** [comment]
Maybe add the shortcuts to the bottom guide, nano style? `Open (^O) Goto (^G)` It'd be a bit cluttered, probably.

**Comment by trogdoro** [comment]
They usually are on the screen. Only it's "Open" with the "O" underlined to
indicate Ctrl+O etc.

--Craig
